version: '3'

services:
  frontend:
    image: frontend_image:latest
    ports:
      - "80:80"
    depends_on:
      - backend
      - database

  backend:
    image: backend_image:latest
    ports:
      - "8080:8080"
    depends_on:
      - database

  database:
    image: database_image:latest
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: my_database
      MYSQL_USER: my_user
      MYSQL_PASSWORD: my_password

